services:
  # PHP & SERVER
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: project_php
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - project_network
    depends_on:
      - postgres
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: project_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - project_network
    depends_on:
      - php

  # DATABASE
  postgres:
    image: postgres:16-alpine
    container_name: project_postgres
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project_network

  # DB Browser (adminer here but you can use any)
  adminer:
    image: adminer
    container_name: pulse_budget_adminer
    ports:
      - "8081:8080"
    networks:
      - project_network
    depends_on:
      - postgres

  # MAIL CATCHER
  mailpit:
    image: axllent/mailpit
    container_name: project_mailpit
    ports:
      - "1080:8025"
      - "1025:1025"
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

volumes:
  postgres_data:
